version: '3'
services:
  react-app:
    build: .
    ports:
      - "3000:3000"      # Expose port 3000 to access the app in the browser
    volumes:
      - .:/app           # Mount the current directory to /app inside the container
      - /app/node_modules # Prevent overwriting node_modules with the host machine's node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix file watching issues on certain environments (e.g., Docker on Windows)
    stdin_open: true       # Keep stdin open (for logging)
    tty: true              # Keep tty open (for better terminal output)
